# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Collect fixed-base Spot manipulation demos with relative EE pose control."""

"""Launch Isaac Sim Simulator first."""

import argparse
from datetime import datetime

from isaaclab.app import AppLauncher


parser = argparse.ArgumentParser(
    description="Collect successful Spot ball-valve demos using heuristic relative IK."
)
parser.add_argument(
    "--num_envs", type=int, default=1, help="Number of environments to simulate."
)
parser.add_argument(
    "--num_demos",
    type=int,
    default=10,
    help="Number of successful demonstrations to collect.",
)
parser.add_argument(
    "--dataset_dir",
    type=str,
    default="logs/recorded_datasets",
    help="Directory in which to write the HDF5 dataset.",
)
parser.add_argument(
    "--dataset_name",
    type=str,
    default=None,
    help="Dataset filename without an extension. A timestamped name is used by default.",
)
parser.add_argument(
    "--reset_state_cache_path",
    type=str,
    default=None,
    help=(
        "Optional reachable Spot valve-reset cache generated by "
        "precompute_spot_reset_states.py."
    ),
)
parser.add_argument(
    "--video", action="store_true", help="Record one video of the collection run."
)
parser.add_argument(
    "--keep_failed_demos",
    action="store_true",
    help="Write rejected episodes to a separate '<dataset_name>_failed.hdf5' file.",
)
parser.add_argument(
    "--video_length",
    type=int,
    default=320,
    help="Length of the recorded video in steps.",
)
parser.add_argument(
    "--position_step",
    type=float,
    default=0.04,
    help="Maximum translation commanded per environment step in meters.",
)
parser.add_argument(
    "--rotation_step",
    type=float,
    default=0.2,
    help="Maximum axis-angle rotation commanded per environment step in radians.",
)
parser.add_argument(
    "--position_gain", type=float, default=1.0, help="Position error gain."
)
parser.add_argument(
    "--rotation_gain", type=float, default=1.0, help="Orientation error gain."
)
parser.add_argument(
    "--max_steps",
    type=int,
    default=None,
    help="Stop after this many total steps even if the demo target has not been reached.",
)
parser.add_argument(
    "--real-time", action="store_true", help="Run in real time, if possible."
)
AppLauncher.add_app_launcher_args(parser)
args_cli = parser.parse_args()

if args_cli.num_envs <= 0:
    parser.error("--num_envs must be greater than zero")
if args_cli.num_demos <= 0:
    parser.error("--num_demos must be greater than zero")
if args_cli.position_step <= 0.0:
    parser.error("--position_step must be greater than zero")
if args_cli.rotation_step <= 0.0:
    parser.error("--rotation_step must be greater than zero")
if args_cli.video:
    args_cli.enable_cameras = True

app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

"""Rest everything follows."""

import os
import time

import gymnasium as gym
import torch
from isaaclab.managers.recorder_manager import DatasetExportMode
from isaaclab.utils.dict import print_dict

from isaaclab_hiveboard.tasks.spot.ball_valve.env import (
    SpotBallValveDeltaEnvCfg_PLAY,
)
from isaaclab_hiveboard.mdp.relative_ee_pose_controller import (
    RelativeEePoseController,
)


TASK_ID = "Spot-Manipulation-Ball-Valve-Delta-Play"


def _register_task() -> None:
    if TASK_ID not in gym.registry:
        gym.register(
            id=TASK_ID,
            entry_point="isaaclab.envs:ManagerBasedRLEnv",
            disable_env_checker=True,
            kwargs={
                "env_cfg_entry_point": (
                    "isaaclab_hiveboard.tasks.spot.ball_valve.env:"
                    "SpotBallValveDeltaEnvCfg_PLAY"
                )
            },
        )


def _dataset_path(dataset_dir: str, dataset_name: str) -> str:
    path = os.path.join(dataset_dir, dataset_name)
    return path if path.endswith(".hdf5") else f"{path}.hdf5"


def main():
    """Collect successful heuristic demonstrations."""
    _register_task()
    env_cfg = SpotBallValveDeltaEnvCfg_PLAY()
    env_cfg.scene.num_envs = args_cli.num_envs
    env_cfg.sim.device = args_cli.device
    env_cfg.actions.arm_action.scale = (
        args_cli.position_step,
        args_cli.position_step,
        args_cli.position_step,
        args_cli.rotation_step,
        args_cli.rotation_step,
        args_cli.rotation_step,
    )
    if args_cli.reset_state_cache_path is not None:
        env_cfg.events.reset_robot_joints.params["reset_state_cache_path"] = (
            os.path.abspath(args_cli.reset_state_cache_path)
        )

    dataset_name = args_cli.dataset_name or (
        f"spot_ball_valve_delta_{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}"
    )
    dataset_dir = os.path.abspath(args_cli.dataset_dir)
    dataset_path = _dataset_path(dataset_dir, dataset_name)
    if os.path.exists(dataset_path):
        raise FileExistsError(f"Refusing to overwrite existing dataset: {dataset_path}")

    env_cfg.recorders.dataset_export_dir_path = dataset_dir
    env_cfg.recorders.dataset_filename = dataset_name
    if args_cli.keep_failed_demos:
        env_cfg.recorders.dataset_export_mode = (
            DatasetExportMode.EXPORT_SUCCEEDED_FAILED_IN_SEPARATE_FILES
        )

    env = gym.make(
        TASK_ID,
        cfg=env_cfg,
        render_mode="rgb_array" if args_cli.video else None,
    )
    if len(env.unwrapped.recorder_manager.active_terms) == 0:
        raise RuntimeError("The collection environment has no active recorder terms.")

    if args_cli.video:
        video_kwargs = {
            "video_folder": os.path.join("videos", "collect_spot_demos"),
            "step_trigger": lambda step: step == 0,
            "video_length": args_cli.video_length,
            "disable_logger": True,
        }
        print("[INFO] Recording collection video.")
        print_dict(video_kwargs, nesting=4)
        env = gym.wrappers.RecordVideo(env, **video_kwargs)

    env.reset()
    controller = RelativeEePoseController(
        env,
        position_step=args_cli.position_step,
        rotation_step=args_cli.rotation_step,
        position_gain=args_cli.position_gain,
        rotation_gain=args_cli.rotation_gain,
    )

    print(f"[INFO] Recording successful demonstrations to: {dataset_path}")
    print(
        f"[INFO] Control frequency: {1.0 / env.unwrapped.step_dt:.1f} Hz. "
        "Relative EE limits: "
        f"position={args_cli.position_step:.4f} m, "
        f"rotation={args_cli.rotation_step:.4f} rad per step."
    )

    recorder = env.unwrapped.recorder_manager
    previous_successes = 0
    previous_failures = 0
    step = 0

    while simulation_app.is_running():
        start_time = time.time()
        with torch.inference_mode():
            actions = controller.compute()
            env.step(actions)
        step += 1

        successes = recorder.exported_successful_episode_count
        failures = recorder.exported_failed_episode_count
        if successes != previous_successes or failures != previous_failures:
            print(
                f"[INFO] Episodes: {successes}/{args_cli.num_demos} successful, "
                f"{failures} rejected."
            )
            previous_successes = successes
            previous_failures = failures

        if successes >= args_cli.num_demos:
            break

        if args_cli.max_steps is not None and step >= args_cli.max_steps:
            raise RuntimeError(
                f"Reached --max_steps={args_cli.max_steps} after collecting "
                f"{successes}/{args_cli.num_demos} successful demonstrations."
            )

        sleep_time = env.unwrapped.step_dt - (time.time() - start_time)
        if args_cli.real_time and sleep_time > 0:
            time.sleep(sleep_time)

    final_successes = recorder.exported_successful_episode_count
    if final_successes < args_cli.num_demos:
        raise RuntimeError(
            "Isaac Sim stopped before collection completed: "
            f"{final_successes}/{args_cli.num_demos} successful demonstrations."
        )

    print(
        f"[INFO] Collection complete: {final_successes} successful "
        f"demonstrations written to {dataset_path}."
    )

    control_freq = 1.0 / env.unwrapped.step_dt
    env.close()

    try:
        from scripts.analyze_dataset import finalize_recorded_dataset
    except ImportError:
        from analyze_dataset import finalize_recorded_dataset

    finalize_recorded_dataset(
        dataset_path=dataset_path,
        control_frequency_hz=control_freq,
        generate_plots=True,
        env_name=TASK_ID,
    )


if __name__ == "__main__":
    main()
